// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuwpXm3E4I9YWaNDvKtFWxsstGqaoB66I',
    appId: '1:114214722974:web:db510f5a85c1b979a54a8f',
    messagingSenderId: '114214722974',
    projectId: 'e-derma',
    authDomain: 'e-derma.firebaseapp.com',
    storageBucket: 'e-derma.firebasestorage.app',
    measurementId: 'G-F5TM3YDVCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgrSO6mXP-VFeBgy7RU7r8Memv1_X5Aeg',
    appId: '1:114214722974:android:3095d25c188dd008a54a8f',
    messagingSenderId: '114214722974',
    projectId: 'e-derma',
    storageBucket: 'e-derma.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAngwsasOKO5FcxQzdyVlnSTvFGQksFxmQ',
    appId: '1:114214722974:ios:0a08d00d61e00fbda54a8f',
    messagingSenderId: '114214722974',
    projectId: 'e-derma',
    storageBucket: 'e-derma.firebasestorage.app',
    iosBundleId: 'com.example.eDerma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuwpXm3E4I9YWaNDvKtFWxsstGqaoB66I',
    appId: '1:114214722974:web:8a5710ec8cd0f381a54a8f',
    messagingSenderId: '114214722974',
    projectId: 'e-derma',
    authDomain: 'e-derma.firebaseapp.com',
    storageBucket: 'e-derma.firebasestorage.app',
    measurementId: 'G-2CQP6HBL26',
  );
}
